server:
  port: 8088

spring:
  application:
    name: ProductApp
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/spring_boot
    username: root
    password: rizal280697